version: '3'
services:
  node:
    image: node:16.14
    container_name: node_container
    tty: true
    stdin_open: true
    restart: always
    ports:
      - 3000:3000
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
  mysql:
    image: mysql:8.0.23
    container_name: mysql_container
    ports:
      - 33060:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
